// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pwdlFdsZHXMR1Mr8q-WU10EFCHnA4mU',
    appId: '1:1007911854604:web:3d36becd8ab6084d118429',
    messagingSenderId: '1007911854604',
    projectId: 'plant-monitor1',
    authDomain: 'plants.smailes.xyz',
    storageBucket: 'plant-monitor1.firebasestorage.app',
    measurementId: 'G-JB1ZZDJ7CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb_CLsGNjt8JOY56PXPw6O1hTfNlrJe3k',
    appId: '1:1007911854604:android:61a4f68e8de901ea118429',
    messagingSenderId: '1007911854604',
    projectId: 'plant-monitor1',
    storageBucket: 'plant-monitor1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpSeUFbEIR1zRuacos_fKqhV9M32_pjM',
    appId: '1:1007911854604:ios:6a75a85b700655ed118429',
    messagingSenderId: '1007911854604',
    projectId: 'plant-monitor1',
    storageBucket: 'plant-monitor1.firebasestorage.app',
    iosClientId: '1007911854604-39a1528r56rfh714g6auair97mr35812.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpSeUFbEIR1zRuacos_fKqhV9M32_pjM',
    appId: '1:1007911854604:ios:6a75a85b700655ed118429',
    messagingSenderId: '1007911854604',
    projectId: 'plant-monitor1',
    storageBucket: 'plant-monitor1.firebasestorage.app',
    iosClientId: '1007911854604-39a1528r56rfh714g6auair97mr35812.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0pwdlFdsZHXMR1Mr8q-WU10EFCHnA4mU',
    appId: '1:1007911854604:web:4ee48198c9cd38ed118429',
    messagingSenderId: '1007911854604',
    projectId: 'plant-monitor1',
    authDomain: 'plants.smailes.xyz',
    storageBucket: 'plant-monitor1.firebasestorage.app',
    measurementId: 'G-QE99HB9QBG',
  );
}